services:
  - type: web
    name: schoolhsp
    env: python
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    autoDeploy: true